/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from  "react"
import { useGLTF } from "@react-three/drei"
import {useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import chessScene from '..assets/3d/chess.glb';

const chess = (props) => {
    const chessRef = useRef();
  const { nodes, materials } = useGLTF(chessScene)
  return (
    <a.group ref={chessRef} {...props} > {/* 'a' group is an Animated group*/}

      <mesh
        geometry={nodes.finallowpoly.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}

      />
    </a.group>
  )
}


export default chess; 